name: 'Publish'

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
        id: build
      - name: Deploy
        uses: ./.github/actions/deploy
        id: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
