name: 'Publish'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: ./.github/actions/build
        id: build
      -
        name: Deploy
        uses: ./.github/actions/deploy
        id: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
